# List of tasks for creating symbolic links
tasks:
  - target: "~/.zshrc"
    source: "zsh/zshrc"

  - target: "~/.zsh"
    source: "zsh"

  #- target: "~/.zgen"
  #  source: "zsh/zgen"

  - target: "~/.tmux"
    source: "tmux"

  - target: "~/.tmux.conf"
    source: "tmux/tmux.conf"

  - target: "~/.vimrc"
    source: "vim/vimrc"

  - target: "~/.config/openssl.conf"
    source: "openssl/openssl.conf"

  - target: "~/.config/nvim"
    source: "nvim"

  - target: "~/.gitconfig"
    source: "git/gitconfig"

  - target: "~/.gitignore"
    source: "git/gitignore_global"

  - target: "~/.config/kitty/kitty.conf"
    source: "kitty/kitty.conf"

  - target: "~/.config/kitty/gruvbox_dark.conf"
    source: "kitty/gruvbox_dark.conf"

  # Linux only
  - target: "~/.config/hypr"
    source: "hypr"
    os: linux

  - target: "~/.config/wofi"
    source: "wofi"
    os: linux

  - target: "~/.Xresources"
    source: "Xresources"
    os: linux

  - target: "~/.xinitrc"
    source: "xinitrc"
    os: linux

  # Darwin only
  - target: "~/.doom.d"
    source: "doom.d"
    os: darwin
