# List of tasks for creating symbolic links
tasks:
  - target: "~/.zshrc"
    source: "zsh/zshrc"

  - target: "~/.zsh"
    source: "zsh"

  #- target: "~/.zgen"
  #  source: "zsh/zgen"

  - target: "~/.tmux"
    source: "tmux"

  - target: "~/.tmux.conf"
    source: "tmux/tmux.conf"

  - target: "~/.vimrc"
    source: "vim/vimrc"

  - target: "~/.config/openssl.conf"
    source: "openssl/openssl.conf"

  - target: "~/.config/nvim"
    source: "nvim"

  - target: "~/.gitconfig"
    source: "git/gitconfig"

  - target: "~/.gitignore"
    source: "git/gitignore_global"

  - target: "~/.config/kitty/kitty.conf"
    source: "kitty/kitty.conf"

  - target: "~/.config/kitty/gruvbox_dark.conf"
    source: "kitty/gruvbox_dark.conf"

  # Linux only
  - target: "~/.config/hypr"
    source: "hypr"
    os: linux

  - target: "~/.config/wofi"
    source: "wofi"
    os: linux

  - target: "~/.Xresources"
    source: "Xresources"
    os: linux

  - target: "~/.xinitrc"
    source: "xinitrc"
    os: linux

  # Darwin only
  - target: "~/.doom.d"
    source: "doom.d"
    os: darwin

fedora:
  dnf:
    - ansible
    - ansible-core
    - zsh-autosuggestions
    - zsh-syntax-highlighting
    - zsh
    - vim-enhanced
    - tmux
    - git
    - gh
    - lazygit
    - python3-dns
    - evolution
    - evolution-data-server
    - evolution-spamassassin
    - syncevolution
    - gcc
    - gcc-c++
    - golang
    - podman-compose
    - docker-compose
    - golang-x-tools-gopls
    - nodejs
    - fd-find
    - ripgrep
    - nmap
    - curl
    - httpie
  pip-packages:
    - pyright
    - pyright
    - rich
    - pynvim
  copr-repo:
    name: "atim/lazygit"

arch:
  pacman:
    - python3-dns
    - evolution
    - evolution-data-server
    - evolution-spamassassin
    - syncevolution
    - gcc
    - gcc-c++
    - golang
    - podman-compose
    - docker-compose
    - golang-x-tools-gopls
    - nodejs
    - fd-find
    - ripgrep
  pip-packages:
    - prompt_toolkit
    - rich
    - pyright
    - pynvim

debian:
  apt:
    - python3-dns
    - evolution
    - evolution-data-server
    - evolution-spamassassin
    - syncevolution
    - gcc
    - gcc-c++
    - golang
    - podman-compose
    - docker-compose
    - golang-x-tools-gopls
    - nodejs
    - fd-find
    - ripgrep
  pip-packages:
    - prompt_toolkit
    - rich
    - pyright
    - pynvim

darwin:
  brew:
    - akamai
    - awscli
    - google-cloud-sdk
    - ansible-language-server
    - ansible
    - ansible-lint
    - python
    - terraform
    - httpie
    - zsh-syntax-highlighting
    - zsh-completions
    - lazygit
    - gtk4
    - libadwaita
    - neovim
    - gcc
    - go
    - colima
    - fd
    - brotli
    - awk
    - autoconf
    - automake
    - meson
    - meson-python
    - ninja
    - node
    - mtr
    - nghttp2
    - wireshark
    - fd
    - ripgrep
  pip-packages:
    - prompt_toolkit
    - rich
    - pyright
    - pynvim
