#!/bin/bash

# Define the default Wofi theme
WOFI_THEME="$HOME/.config/wofi/themes/gruvbox.css"

# Function to display help
doc() {
    echo "Usage:
    exec_wofi [Options]

    Options:
        app_launcher    Runs wofi application launcher
        ssh             Runs wofi ssh menu
        power           Runs wofi power menu"
}

# Kill any existing wofi instance
killall wofi

# Main script logic
case $1 in
  app_launcher)
    wofi --show drun --style "$WOFI_THEME"
    ;;
  ssh)
    ~/.config/hypr/scripts/wofi-ssh.sh
    ;;
  power)
    ~/.config/hypr/scripts/wofi-power.sh
    ;;
  *)
    doc
    ;;
esac