" Plugins
"""""""""""""""""""""""""""""""
set nocompatible
filetype off
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Plugins
""""""""""""""""""""""""""""""""
Plugin 'jacoborus/tender'
Plugin 'tpope/vim-endwise'
Plugin 'tpope/vim-git'
Plugin 'tpope/vim-surround'
Plugin 'fatih/vim-go'
Plugin 'Blackrush/vim-gocode'
Plugin 'tpope/vim-fugitive'
Plugin 'Yggdroot/indentLine'
Plugin 'airblade/vim-gitgutter'
Plugin 'jstemmer/gotags'
Plugin 'majutsushi/tagbar'
Plugin 'scrooloose/nerdtree'
Plugin 'pearofducks/ansible-vim'
Plugin 'smerrill/vcl-vim-plugin'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'ryanoasis/vim-devicons'
Plugin 'kristijanhusak/vim-hybrid-material'
Plugin 'lepture/vim-jinja'
" Some JavaScript plugins
Plugin 'maralla/completor.vim'
Plugin 'pangloss/vim-javascript'
Plugin 'sheerun/vim-polyglot'
Plugin 'mxw/vim-jsx'
Plugin 'othree/yajs.vim'
Plugin 'w0rp/ale'
call vundle#end() 

" Send more characters for redraws
set ttyfast

" Enable mouse use in all modes
"set mouse=a

" colorscheme settings
""""""""""""""""""""""""""""""""
set termguicolors             " enable truecolor
syntax enable
set background=dark
try
    colorscheme hybrid_material
catch
    colorscheme default
endtry
let g:enable_bold_font = 1
let g:enable_italic_font = 0

" vim-airline settings
""""""""""""""""""""""""""""""""

let g:airline_powerline_fonts = 0
let g:airline_theme='hybrid'

" vim-airline straight tabs
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'

if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline_symbols.space = "\ua0"

" JavaScript settings
""""""""""""""""""""""""""""""""
autocmd FileType javascript set formatprg=prettier\ --stdin
let g:completor_node_binary = '/usr/bin/node'


" Python Settings
""""""""""""""""""""""""""""""""
" python autocomplete settings required jedi package
" $ pip install jedi 
let g:completor_python_binary = '/usr/lib/python3.6/'


" tagbar settings
""""""""""""""""""""""""""""""""
nmap <C-t> :TagbarToggle<CR>

" disable auto comment insertion
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" gotags
let g:tagbar_type_go = {
    \ 'ctagstype' : 'go',
    \ 'kinds'     : [
        \ 'p:package',
        \ 'i:imports:1',
        \ 'c:constants',
        \ 'v:variables',
        \ 't:types',
        \ 'n:interfaces',
        \ 'w:fields',
        \ 'e:embedded',
        \ 'm:methods',
        \ 'r:constructor',
        \ 'f:functions'
    \ ],
    \ 'sro' : '.',
    \ 'kind2scope' : {
        \ 't' : 'ctype',
        \ 'n' : 'ntype'
    \ },
    \ 'scope2kind' : {
        \ 'ctype' : 't',
        \ 'ntype' : 'n'
    \ },
    \ 'ctagsbin'  : 'gotags',
    \ 'ctagsargs' : '-sort -silent'
    \ }

" NERDTree settings
""""""""""""""""""""""""""""""""

" bind ctrl+n to open/close nerdtree.
map <C-n> :NERDTreeToggle<CR>

" close vim if nerdtree is the only open window.
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") &&  b:NERDTreeType == "primary") | q | endif

" Open nerdtree automatically if no files were specified to be opened
"autocmd StdinReadPre * let s:std_in=1
"autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" Open nerdtree when vim starts with a directory specified to be opened
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif

" speed up the annoying parens & bracket matching speed
set showmatch
set matchtime=0

" Only do this part when compiled with support for autocommands.
if has("autocmd")
    " Use filetype detection and file-based automatic indenting.
    filetype plugin indent on

    " Use actual tab chars in Makefiles.
    autocmd FileType make set tabstop=8 shiftwidth=8 softtabstop=0 noexpandtab
endif

" For everything else, use a tab width of 4 space col.
set tabstop=4                 " The width of a TAB is set to 4.
                              " Still it is a \t. It is just that
                              " Vim will interpret it to be having
                              " a width of 4.
set shiftwidth=4              " Indents will have a width of 4.
set softtabstop=4             " Sets the number of columns for a TAB.
set expandtab                 " Expand TABs to spaces.
syntax on

" Look & Feel
"""""""""""""""""""""""""""""""
if &term =~# '^screen'
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif

set ruler                     " show the line number on the bar
set more                      " use more prompt
set autoread                  " watch for file changes
highlight Normal ctermbg=NONE
highlight nonText ctermbg=NONE

" indentLine settings
let g:indentLine_char = ' '
"let g:indentLine_color_term = 235
" vim-gitgutter settings
highlight SignColumn ctermbg=233
set encoding=utf-8
set t_Co=256
"set fillchars+=stl:\ ,stlnc:\
"set number                    " line numbers
if has("gui_running")
   let s:uname = system("uname")
   if s:uname == "Darwin\n"
      set guifont=DejaVu\ Sans\ Mono\ for\ Powerline:h14
   endif
endif

" General settings
"""""""""""""""""""""""""""""""
set hidden
set noautowrite               " don't automagically write on :next
set lazyredraw                " don't redraw when don't have to
set showmode
set showcmd
set nocompatible              " vim, not vi
set scrolloff=5               " keep at least 5 lines above/below
set sidescrolloff=5           " keep at least 5 lines left/right
set history=200
set backspace=indent,eol,start
set linebreak
set cmdheight=2               " command line two lines high
set undolevels=1000           " 1000 undos
set updatecount=100           " switch every 100 chars
set complete=.,w,b,u,U,t,i,d  " do lots of scanning on tab completion
set ttyfast                   " we have a fast terminal
set noerrorbells              " No error bells please
set shell=zsh
set fileformats=unix
set ff=unix
set wildmode=longest:full
set wildmenu                  " menu has tab completion
let maplocalleader=','        " all my macros start with ,
set laststatus=2
set nowrap

" Searching
"""""""""""""""""""""""""""""""
set incsearch                 " incremental search
set ignorecase                " search ignoring case
set hlsearch                  " highlight the search
set showmatch                 " show matching bracket
set diffopt=filler,iwhite     " ignore all whitespace and sync
  
" Backup
"""""""""""""""""""""""""""""""
set backup
set backupdir=~/.vim/backup

" Ansible plugin options
"""""""""""""""""""""""""""""""
let g:ansible_options = {'ignore_blank_lines': 0}
let g:ansible_extra_keywords_highlight = 1
let g:ansible_template_syntaxes = 1

au BufRead,BufNewFile *.j2 set filetype=ansible

" Define command history
"""""""""""""""""""""""""""""""
let &viminfo='%,h,"4,''4,f0,/99,:' . &history 
"           | |  |   |  |  |       +command-line history saved 
"           | |  |   |  |  +search history saved 
"           | |  |   |  +marks 0-9,A-Z 0=NOT saved 
"           | |  |   +files saved for marks 
"           | |  +lines saved each register (old name for <, vi6.2) 
"           | +disable 'hlsearch' loading viminfo 
"           +save/restore buffer list 

" Spelling
if v:version >= 700
  " Enable spell check for text files
  autocmd BufNewFile,BufRead *.txt setlocal spell spelllang=en
endif

" Mappings
"""""""""""""""""""""""""""""""
" toggle list mode
nmap <LocalLeader>tl :set list!<cr>
" toggle paste mode
nmap <LocalLeader>pp :set paste!<cr>
