#!/usr/bin/env bash
# render html as markdown and display in glow, supports syntax highlighting
# requires: pandoc, glow
# author: CEUK
# Use pandoc to convert HTML to Markdown (better preservation of structure than html2text)
pandoc -f html -t markdown --wrap=none "$1" > /tmp/mutt.md
glow -s ~/.config/glow/email.json /tmp/mutt.md
