#!/usr/bin/env bash
# render html to text using w3m, optimized for best rendering
# Note: This will not show link URLs inline. Use urlscan (\\cl) to see and open links.
w3m -dump -T text/html -s -graph -cols 10000 "$1"
