return {
  s("playbook", {
    t({
      "- name: ",
    }),
    i(1, "Playbook Name"),
    t({ "", "  hosts: " }),
    i(2, "all"),
    t({ "", "  become: " }),
    i(3, "yes"),
    t({ "", "  tasks:", "    - name: " }),
    i(4, "Task Name"),
    t({ "", "      " }),
    i(5, "ping:"),
    t({ "" }),
  }),
  s("task", {
    t({
      "- name: ",
    }),
    i(1, "Task Name"),
    t({ "", "  " }),
    i(2, "module_name:"),
    t({ "", "    " }),
    i(3, "arg1: value1"),
    t({ "" }),
  }),
  s("apt", {
    t({
      "- name: Install ",
    }),
    i(1, "package"),
    t({ "", "  ansible.builtin.apt:", "    name: " }),
    rep(1),
    t({ "", "    state: " }),
    i(2, "present"),
    t({ "", "    update_cache: yes" }),
  }),
  s("yum", {
    t({
      "- name: Install ",
    }),
    i(1, "package"),
    t({ "", "  ansible.builtin.yum:", "    name: " }),
    rep(1),
    t({ "", "    state: " }),
    i(2, "present"),
    t({ "" }),
  }),
  s("service", {
    t({
      "- name: Ensure ",
    }),
    i(1, "service"),
    t({ " is running", "  ansible.builtin.service:", "    name: " }),
    rep(1),
    t({ "", "    state: started", "    enabled: yes" }),
  }),
  s("copy", {
    t({
      "- name: Copy file to remote node",
      "  ansible.builtin.copy:",
      "    src: ",
    }),
    i(1, "/path/to/local/file"),
    t({ "", "    dest: " }),
    i(2, "/path/to/remote/file"),
    t({ "", "    owner: " }),
    i(3, "root"),
    t({ "", "    group: " }),
    i(4, "root"),
    t({ "", "    mode: '" }),
    i(5, "0644"),
    t({ "'" }),
  }),
  s("template", {
    t({
      "- name: Template a file",
      "  ansible.builtin.template:",
      "    src: ",
    }),
    i(1, "template.j2"),
    t({ "", "    dest: " }),
    i(2, "/etc/config.file"),
    t({ "", "    owner: " }),
    i(3, "root"),
    t({ "", "    mode: '" }),
    i(4, "0644"),
    t({ "'" }),
  }),
  s("file", {
    t({
      "- name: Change file ownership, group and permissions",
      "  ansible.builtin.file:",
      "    path: ",
    }),
    i(1, "/etc/foo.conf"),
    t({ "", "    owner: " }),
    i(2, "foo"),
    t({ "", "    group: " }),
    i(3, "foo"),
    t({ "", "    mode: '" }),
    i(4, "0644"),
    t({ "'" }),
  }),
  s("debug", {
    t({
      "- name: Print debug message",
      "  ansible.builtin.debug:",
      '    msg: "',
    }),
    i(1, "Hello World!"),
    t({ '"' }),
  }),
  s("shell", {
    t({
      "- name: Execute shell command",
      "  ansible.builtin.shell: ",
    }),
    i(1, "ls -l /tmp"),
    t({ "", "  register: " }),
    i(2, "shell_output"),
    t({ "" }),
  }),
  s("cron", {
    t({
      "- name: Ensure a job that runs at 2 and 5 today",
      "  ansible.builtin.cron:",
      "    name: ",
    }),
    i(1, "check dirs"),
    t({ "", "    minute: " }),
    i(2, "0"),
    t({ "", "    hour: " }),
    i(3, "5,2"),
    t({ "", "    job: " }),
    i(4, "ls -alh > /dev/null"),
    t({ "" }),
  }),
  s("lineinfile", {
    t({
      "- name: Ensure SELinux is set to enforcing mode",
      "  ansible.builtin.lineinfile:",
      "    path: ",
    }),
    i(1, "/etc/selinux/config"),
    t({ "", "    regexp: " }),
    i(2, "^SELINUX="),
    t({ "", "    line: " }),
    i(3, "SELINUX=enforcing"),
    t({ "" }),
  }),
}
