return {
  s("main", {
    t({
      "#include <stdio.h>",
      "",
      "int main(int argc, char *argv[]) {",
      "  ",
      "  return 0;",
      "}",
    }),
  }),
  s("for", {
    t({ "for (int " }),
    i(1, "i"),
    t({ " = 0; " }),
    rep(1),
    t({ " < " }),
    i(2, "count"),
    t({ "; " }),
    rep(1),
    t({ "++) {", "    " }),
    i(3, "code();"),
    t({ "", "}" }),
  }),
  s("if", {
    t({ "if (" }),
    i(1, "condition"),
    t({ ") {", "    " }),
    i(2, "code();"),
    t({ "", "}" }),
  }),
  s("ifelse", {
    t({ "if (" }),
    i(1, "condition"),
    t({ ") {", "    " }),
    i(2, "code();"),
    t({ "", "} else {", "    " }),
    i(3, "other();"),
    t({ "", "}" }),
  }),
  s("while", {
    t({ "while (" }),
    i(1, "condition"),
    t({ ") {", "    " }),
    i(2, "code();"),
    t({ "", "}" }),
  }),
  s("do", {
    t({ "do {", "    " }),
    i(2, "code();"),
    t({ "", "} while (" }),
    i(1, "condition"),
    t({ ");" }),
  }),
  s("func", {
    i(1, "void"),
    t({ " " }),
    i(2, "function_name"),
    t({ "(" }),
    i(3, "args"),
    t({ ") {", "    " }),
    i(4, "code();"),
    t({ "", "}" }),
  }),
  s("struct", {
    t({ "struct " }),
    i(1, "Name"),
    t({ " {", "    " }),
    i(2, "int field;"),
    t({ "", "};" }),
  }),
  s("typedef", {
    t({ "typedef struct " }),
    i(1, "Name"),
    t({ " {", "    " }),
    i(2, "int field;"),
    t({ "", "} " }),
    rep(1),
    t({ "_t;" }),
  }),
  s("printf", {
    t({ 'printf("' }),
    i(1, "Hello, %s!\\n"),
    t({ '", ' }),
    i(2, "var"),
    t({ ");" }),
  }),
  s("include", {
    t({ "#include <" }),
    i(1, "stdio.h"),
    t({ ">" }),
  }),
}
