return {
  s("main", {
    t({
      "package main",
      "",
      'import "fmt"',
      "",
      "func main() {",
      '    fmt.Println("Hello, world!")',
      "}",
    }),
  }),
  s("func", {
    t({ "func " }),
    i(1, "name"),
    t({ "(" }),
    i(2, "args"),
    t({ ") " }),
    i(3, "error"),
    t({ " {", "    " }),
    i(4, "return nil"),
    t({ "", "}" }),
  }),
  s("iferr", {
    t({ "if err != nil {", "    return " }),
    i(1, "err"),
    t({ "", "}" }),
  }),
  s("for", {
    t({ "for " }),
    i(1, "i := 0"),
    t({ "; " }),
    i(2, "i < count"),
    t({ "; " }),
    i(3, "i++"),
    t({ " {", "    " }),
    i(4, "fmt.Println(i)"),
    t({ "", "}" }),
  }),
  s("forr", {
    t({ "for " }),
    i(1, "i"),
    t({ ", " }),
    i(2, "v"),
    t({ " := range " }),
    i(3, "iterable"),
    t({ " {", "    " }),
    i(4, "fmt.Println(i, v)"),
    t({ "", "}" }),
  }),
  s("struct", {
    t({ "type " }),
    i(1, "Name"),
    t({ " struct {", "    " }),
    i(2, "Field string"),
    t({ "", "}" }),
  }),
  s("interface", {
    t({ "type " }),
    i(1, "Name"),
    t({ " interface {", "    " }),
    i(2, "Method() error"),
    t({ "", "}" }),
  }),
  s("switch", {
    t({ "switch " }),
    i(1, "expr"),
    t({ " {", "case " }),
    i(2, "val"),
    t({ ":", "    " }),
    i(3, "fmt.Println(val)"),
    t({ "", "default:", "    " }),
    i(4, 'fmt.Println("default")'),
    t({ "", "}" }),
  }),
  s("select", {
    t({ "select {", "case " }),
    i(1, "msg := <-ch"),
    t({ ":", "    " }),
    i(2, "fmt.Println(msg)"),
    t({ "", "default:", "    " }),
    i(3, 'fmt.Println("default")'),
    t({ "", "}" }),
  }),
  s("go", {
    t({ "go func() {", "    " }),
    i(1, 'fmt.Println("goroutine")'),
    t({ "", "}()" }),
  }),
  s("defer", {
    t({ "defer " }),
    i(1, "file.Close()"),
  }),
}
