return {
  s("html", {
    t({
      "<!DOCTYPE html>",
      '<html lang="en">',
      "<head>",
      '    <meta charset="UTF-8">',
      '    <meta name="viewport" content="width=device-width, initial-scale=1.0">',
      "    <title>",
    }),
    i(1, "Document"),
    t({ "</title>", "</head>", "<body>", "    " }),
    i(2),
    t({ "", "</body>", "</html>" }),
  }),
  s("div", {
    t({ '<div class="' }),
    i(1, "container"),
    t({ '">', "    " }),
    i(2),
    t({ "", "</div>" }),
  }),
  s("a", {
    t({ '<a href="' }),
    i(1, "#"),
    t({ '">' }),
    i(2, "Link"),
    t({ "</a>" }),
  }),
  s("img", {
    t({ '<img src="' }),
    i(1, "image.png"),
    t({ '" alt="' }),
    i(2, "description"),
    t({ '">' }),
  }),
  s("ul", {
    t({ "<ul>", "    <li>" }),
    i(1, "Item"),
    t({ "</li>", "</ul>" }),
  }),
  s("li", {
    t({ "<li>" }),
    i(1, "Item"),
    t({ "</li>" }),
  }),
  s("p", {
    t({ "<p>" }),
    i(1, "Paragraph"),
    t({ "</p>" }),
  }),
  s("span", {
    t({ '<span class="' }),
    i(1, "class"),
    t({ '">' }),
    i(2, "Text"),
    t({ "</span>" }),
  }),
  s("h1", {
    t({ "<h1>" }),
    i(1, "Heading"),
    t({ "</h1>" }),
  }),
  s("form", {
    t({ '<form action="' }),
    i(1, "/submit"),
    t({ '" method="' }),
    i(2, "POST"),
    t({ '">', "    " }),
    i(3),
    t({ "", "</form>" }),
  }),
  s("input", {
    t({ '<input type="' }),
    i(1, "text"),
    t({ '" name="' }),
    i(2, "name"),
    t({ '" placeholder="' }),
    i(3, "Placeholder"),
    t({ '">' }),
  }),
  s("button", {
    t({ '<button type="' }),
    i(1, "submit"),
    t({ '">' }),
    i(2, "Submit"),
    t({ "</button>" }),
  }),
  s("script", {
    t({ '<script src="' }),
    i(1, "script.js"),
    t({ '"></script>' }),
  }),
  s("link", {
    t({ '<link rel="stylesheet" href="' }),
    i(1, "style.css"),
    t({ '">' }),
  }),
}
