return {
	s("main", {
		t({
			"fn main() {",
			'  println!("Hello, world!");',
			"}",
		}),
	}),
	s("test", {
		t({
			"#[cfg(test)]",
			"mod tests {",
			"    use super::*;",
			"",
			"    #[test]",
			"    fn ",
			i(1, "test_name"),
			"() {",
			"        assert_eq!(",
			i(2, "expected"),
			", ",
			i(3, "actual"),
			");",
			"    }",
			"}",
		}),
	}),
	s("fn", {
		t({ "fn " }),
		i(1, "name"),
		t({ "(" }),
		i(2, "args"),
		t({ ") -> " }),
		i(3, "ReturnType"),
		t({ " {", "    " }),
		i(4, "todo!()"),
		t({ "", "}" }),
	}),
	s("struct", {
		t({ "struct " }),
		i(1, "Name"),
		t({ " {", "    " }),
		i(2, "field: Type,"),
		t({ "", "}" }),
	}),
	s("impl", {
		t({ "impl " }),
		i(1, "Name"),
		t({ " {", "    fn new() -> Self {", "        Self {", "            " }),
		i(2, "todo!()"),
		t({ "", "        }", "    }", "}" }),
	}),
	s("enum", {
		t({ "enum " }),
		i(1, "Name"),
		t({ " {", "    " }),
		i(2, "Variant,"),
		t({ "", "}" }),
	}),
	s("match", {
		t({ "match " }),
		i(1, "expr"),
		t({ " {", "    " }),
		i(2, "Pattern"),
		t({ " => " }),
		i(3, "expr,"),
		t({ "", "    _ => " }),
		i(4, "todo!()"),
		t({ ",", "}" }),
	}),
	s("print", {
		t({ 'println!("' }),
		i(1, "{}"),
		t({ '", ' }),
		i(2, "val"),
		t({ ");" }),
	}),
	s("format", {
		t({ 'format!("' }),
		i(1, "{}"),
		t({ '", ' }),
		i(2, "val"),
		t({ ")" }),
	}),
	s("dbg", {
		t({ "dbg!(" }),
		i(1, "val"),
		t({ ");" }),
	}),
	s("derive", {
		t({ "#[derive(" }),
		i(1, "Debug, Clone, PartialEq"),
		t({ ")]" }),
	}),
	s("trait", {
		t({ "trait " }),
		i(1, "Name"),
		t({ " {", "    fn " }),
		i(2, "method"),
		t({ "(&self);" }),
		t({ "", "}" }),
	}),
}
