return {
	s("shebang", {
		t({
			"#!/bin/bash",
			"set -euo pipefail",
			"IFS=$'\\n\\t'",
		}),
	}),
	s("main", {
		t({
			"main() {",
			"  ",
			"}",
			"",
			'main "$@"',
		}),
	}),
	s("if", {
		t({ "if [ " }),
		i(1, "condition"),
		t({ " ]; then", "    " }),
		i(2, "echo 'yes'"),
		t({ "", "fi" }),
	}),
	s("ifelse", {
		t({ "if [ " }),
		i(1, "condition"),
		t({ " ]; then", "    " }),
		i(2, "echo 'yes'"),
		t({ "", "else", "    " }),
		i(3, "echo 'no'"),
		t({ "", "fi" }),
	}),
	s("for", {
		t({ "for " }),
		i(1, "item"),
		t({ " in " }),
		i(2, "list"),
		t({ "; do", "    " }),
		i(3, 'echo "$item"'),
		t({ "", "done" }),
	}),
	s("fori", {
		t({ "for ((" }),
		i(1, "i=0"),
		t({ "; " }),
		i(2, "i<10"),
		t({ "; " }),
		i(3, "i++"),
		t({ ")); do", "    " }),
		i(4, 'echo "$i"'),
		t({ "", "done" }),
	}),
	s("while", {
		t({ "while " }),
		i(1, "[ condition ]"),
		t({ "; do", "    " }),
		i(2, "echo 'loop'"),
		t({ "", "done" }),
	}),
	s("func", {
		i(1, "function_name"),
		t({ "() {", "    " }),
		i(2, "echo 'function body'"),
		t({ "", "}" }),
	}),
	s("case", {
		t({ "case " }),
		i(1, '"$var"'),
		t({ " in", "    " }),
		i(2, "pattern"),
		t({ ")", "        " }),
		i(3, "echo 'match'"),
		t({ "", "        ;;", "    *)", "        " }),
		i(4, "echo 'default'"),
		t({ "", "        ;;", "esac" }),
	}),
	s("read", {
		t({ 'read -r -p "' }),
		i(1, "Prompt: "),
		t({ '" ' }),
		i(2, "var_name"),
	}),
	s("check_dir", {
		t({ 'if [ ! -d "' }),
		i(1, "directory_path"),
		t({ '" ]; then', '    mkdir -p "' }),
		rep(1),
		t({ '"', "fi" }),
	}),
	s("check_file", {
		t({ 'if [ -f "' }),
		i(1, "file_path"),
		t({ '" ]; then', "    " }),
		i(2, "echo 'exists'"),
		t({ "", "fi" }),
	}),
}
