return {
  s("pod", {
    t({
      "apiVersion: v1",
      "kind: Pod",
      "metadata:",
      "  name: ",
    }),
    i(1, "mypod"),
    t({ "", "  labels:", "    app: " }),
    i(2, "myapp"),
    t({ "", "spec:", "  containers:", "  - name: " }),
    i(3, "mycontainer"),
    t({ "", "    image: " }),
    i(4, "nginx:latest"),
    t({ "", "    ports:", "    - containerPort: " }),
    i(5, "80"),
    t({ "" }),
  }),
  s("deployment", {
    t({
      "apiVersion: apps/v1",
      "kind: Deployment",
      "metadata:",
      "  name: ",
    }),
    i(1, "mydeployment"),
    t({ "", "spec:", "  replicas: " }),
    i(2, "3"),
    t({ "", "  selector:", "    matchLabels:", "      app: " }),
    i(3, "myapp"),
    t({ "", "  template:", "    metadata:", "      labels:", "        app: " }),
    rep(3),
    t({ "", "    spec:", "      containers:", "      - name: " }),
    i(4, "mycontainer"),
    t({ "", "        image: " }),
    i(5, "nginx:latest"),
    t({ "", "        ports:", "        - containerPort: " }),
    i(6, "80"),
    t({ "" }),
  }),
  s("service", {
    t({
      "apiVersion: v1",
      "kind: Service",
      "metadata:",
      "  name: ",
    }),
    i(1, "myservice"),
    t({ "", "spec:", "  selector:", "    app: " }),
    i(2, "myapp"),
    t({ "", "  ports:", "  - protocol: TCP", "    port: " }),
    i(3, "80"),
    t({ "", "    targetPort: " }),
    i(4, "80"),
    t({ "" }),
  }),
  s("configmap", {
    t({
      "apiVersion: v1",
      "kind: ConfigMap",
      "metadata:",
      "  name: ",
    }),
    i(1, "myconfigmap"),
    t({ "", "data:", "  " }),
    i(2, "key"),
    t({ ": " }),
    i(3, "value"),
    t({ "" }),
  }),
  s("secret", {
    t({
      "apiVersion: v1",
      "kind: Secret",
      "metadata:",
      "  name: ",
    }),
    i(1, "mysecret"),
    t({ "", "type: Opaque", "data:", "  " }),
    i(2, "key"),
    t({ ": " }),
    i(3, "base64encodedvalue"),
    t({ "" }),
  }),
  s("ingress", {
    t({
      "apiVersion: networking.k8s.io/v1",
      "kind: Ingress",
      "metadata:",
      "  name: ",
    }),
    i(1, "myingress"),
    t({ "", "spec:", "  rules:", "  - host: " }),
    i(2, "myapp.example.com"),
    t({
      "",
      "    http:",
      "      paths:",
      "      - path: /",
      "        pathType: Prefix",
      "        backend:",
      "          service:",
      "            name: ",
    }),
    i(3, "myservice"),
    t({ "", "            port:", "              number: " }),
    i(4, "80"),
    t({ "" }),
  }),
  s("pv", {
    t({
      "apiVersion: v1",
      "kind: PersistentVolume",
      "metadata:",
      "  name: ",
    }),
    i(1, "mypv"),
    t({ "", "spec:", "  capacity:", "    storage: " }),
    i(2, "5Gi"),
    t({ "", "  accessModes:", "    - ReadWriteOnce", "  hostPath:", "    path: " }),
    i(3, "/mnt/data"),
    t({ "" }),
  }),
  s("pvc", {
    t({
      "apiVersion: v1",
      "kind: PersistentVolumeClaim",
      "metadata:",
      "  name: ",
    }),
    i(1, "mypvc"),
    t({
      "",
      "spec:",
      "  accessModes:",
      "    - ReadWriteOnce",
      "  resources:",
      "    requests:",
      "      storage: ",
    }),
    i(2, "5Gi"),
    t({ "" }),
  }),
  s("cronjob", {
    t({
      "apiVersion: batch/v1",
      "kind: CronJob",
      "metadata:",
      "  name: ",
    }),
    i(1, "mycronjob"),
    t({ "", "spec:", '  schedule: "' }),
    i(2, "* * * * *"),
    t({
      '"',
      "  jobTemplate:",
      "    spec:",
      "      template:",
      "        spec:",
      "          containers:",
      "          - name: ",
    }),
    i(3, "mycontainer"),
    t({ "", "            image: " }),
    i(4, "busybox"),
    t({
      "",
      "            imagePullPolicy: IfNotPresent",
      "            command:",
      "            - /bin/sh",
      "            - -c",
      "            - ",
    }),
    i(5, "date; echo Hello from the Kubernetes cluster"),
    t({ "", "          restartPolicy: OnFailure" }),
  }),
  s("namespace", {
    t({
      "apiVersion: v1",
      "kind: Namespace",
      "metadata:",
      "  name: ",
    }),
    i(1, "mynamespace"),
    t({ "" }),
  }),
}
