wsl = false
theme = "dark"

[font]
  normal = ["Iosevka Nerd Font"]
  size = 14.0

[window]
  padding = {top = 10, left = 10, right = 10, bottom = 10}
  decorations = "none"
  title_hidden = true

[visual_effects]
  blur = true
  contrast = 1.0
  gamma = 1.0
  saturation = 1.0
  trail_effect = "railgun"
  trail_density = 10

[cursor]
  animation_length = 0.05
  blink_animation = "solid"
  blink_interval = 500
  hide_on_typing = true
  unfocused_style = "block"

# For more options, see the Neovide documentation:
# https://neovide.dev/configuration.html
